### PR TITLE
Added Codeigniter3

### LINKED ISSUE #23: Add base repo for php-codeigniter

### PR DESCRIPTION
**Pull request by smartclash**
Added codeigniter3. Named the microservice particularly with a prefix 3 because version 4 is under heavy development and people use it too. So, will create another PR for adding codeingiter4.

Fixes https://github.com/hasura/quickstart-docker-git/issues/23

### CODE REVIEW

**Comment by smartclash** [comment]
Oops, don't merge this PR yet. I am testing it. But it seems like this is not working. I get this error whenever I try to push the microservice. Any solutions?

problemwithcustommicroservice

**Comment by coco98** [comment]
@smartclash Is the k8s.yaml file missing? 
Can you tell me what process you followed to test?

**Comment by smartclash** [comment]
I first create a microservice via `hasura ms create ci` and then added the routes and remotes as it was stated. Then I copied the `Dockerfile` and `app` folder and pasted it in there. Then, I added all the files via the `git add .` followed by a commit and `hasura conf apply`. Then finally I pushed the repo to hasura master where at last I got that error @coco98

**Comment by coco98** [comment]
Can you paste the last bits of your `conf/ci.yaml` here? And can you also paste the entire `k8s.yaml` here? This should not happen. Super weird.

**Comment by smartclash** [comment]
Same happens to laravel (`php-laravel`). Only change is that I created a microservice via this command 
```
hasura ms create laravel --template=php-laravel
```

and followed other instructions as stated.

**Comment by smartclash** [comment]
File: `ci.yaml`
```yaml
registry: {{ cluster.metadata.registry|json }}
remotes:
  # Default remote to push code and configuration
  {{ cluster.name }}:
    <<: {}
    '{{ cluster.metadata.namespaces.user }}.api':
      api:
        dockerfile: microservices/api/Dockerfile
        path: microservices/api
    '{{ cluster.metadata.namespaces.user }}.laravel':
      www:
        dockerfile: microservices/laravel/Dockerfile
        path: microservices/laravel
    '{{ cluster.metadata.namespaces.user }}.ci':
      ci:
        dockerfile: microservices/ci/Dockerfile
        path: microservices/ci
```

File: `k8s.yaml`
```yaml
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: ci
      hasuraService: custom
    name: ci
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ci
      spec:
        containers:
        - image: hasura/base-git-image:0.7
          imagePullPolicy: IfNotPresent
          name: ci
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ci
      hasuraService: custom
    name: ci
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: ci
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
```

Here you go @coco98

**Comment by coco98** [comment]
@shahidhk @arvi3411301 Do you guys know what error this is?

**Comment by smartclash** [comment]
Should I open a new issue so that we can better collaborate on this? @coco98

**Comment by coco98** [comment]
@smartclash I tried php-laravel, seems to work perfectly fine. https://laravel.blandishment31.hasura-app.io/

Can you share your current project with me via github? Also, add me as a collaborator to your cluster temporarily? (tanmaig@hasura.io) Let's debug this weirdness :/

**Comment by smartclash** [comment]
Invited you as a collabrator at Hasura and github. Here you go https://github.com/smartclash/creepy-errors-here-i-come/invitations. And, should I invite those two guys too :thinking:? @coco98

**Comment by coco98** [comment]
@smartclash So I deployed your project to my cluster. Everything seems to work fine: 
https://ci.blandishment31.hasura-app.io/
https://laravel.blandishment31.hasura-app.io/

Can you try emptying your clusters.yaml and adding a new cluster to it? cluster create, cluster add and so forth?

**Comment by smartclash** [comment]
Well, the cluster I am trying to deploy these microservices are being used for HPDF project. I have no problem in deleteing the cluster. But I have submited the link. So, if I delete the project, then they might not be able to view it. What if I create a new project and then try @coco98?

**Comment by coco98** [comment]
@smartclash Actually you don't need to do that. Jsut do this:

```
hasura cluster create 
hasura cluster add <name> -c hasura-test
hasura ssh-key add -c hasura-test
git push hasura-test master
```

That should work.

**Comment by smartclash** [comment]
Damn, that was a bad luck either. @coco98 

Created a new cluster, made that default, added ssh keys and pushed everything to it. Then, I got this weird error. And for your information, I created the cluster using `--type=hpdf` just to make sure the error is with DANAVA.

```
remote: Updating Kubernetes deployment: api
remote: Error from server (NotFound): deployments.extensions "api" not found
To ssh://fetching72.hasura-app.io:2450/~/git/fetching72
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://hasura@fetching72.hasura-app.io:2450/~/git/fetching72'
```

Anyways, at least I am happy that my PR works awesome on your end :P

**Comment by coco98** [comment]
@smartclash I feel like we're getting close! Two things to try:

1) Can you remove laravel and api folders from microservices. Only keep the ci folder. Then GPHM and check if it works?
2) Can you create another cluster (not type=hpdf) and just check to ensure?

**Comment by smartclash** [comment]
Sure, will do that and get back to you @coco98.

**Comment by smartclash** [comment]
Gotcha, it is working in normal free tier. The problem is with DANAVA. Check that out here https://ci.backwardly20.hasura-app.io/. 

And yeah, this makes my PR tested and is now healthy to get merged. Thanks. But have any idea why it was not working over in the DANAVA cluster? Probably a bug? @coco98

**Pull request closed without merging**
